"""
engine/execution.py - Order Execution Interface
===============================================

Handles the execution of orders generated by the Strategy.
Supports Simulated Execution (Backtest) and Live Execution (CCXT).
"""

import abc
from loguru import logger
from engine.events import Event, EventType
from engine.order import Order, OrderType, OrderStatus

class ExecutionHandler(abc.ABC):
    """Abstract interface for executing orders."""
    
    @abc.abstractmethod
    def execute_order(self, event: Event) -> None:
        """
        Takes an ORDER event and executes it.
        For simulation, it might just log or fill immediately.
        For live, it sends API request.
        """
        pass

class SimulatedExecutionHandler(ExecutionHandler):
    """
    Simulates execution. 
    In BacktestEngine, this is partly handled by FillSimulator, 
    but for a 'Live' Paper Trading mode without real connection, 
    we can use this to just log 'Filled'.
    """
    def __init__(self, engine):
        self.engine = engine # Reference to update portfolio directly if needed
        
    def execute_order(self, event: Event) -> None:
        if event.type != EventType.ORDER:
            return
            
        order: Order = event.data
        logger.info(f"SIMULATED EXECUTION: {order}")
        
        # In a real event loop, we would generate a FILL event here
        # or let the FillSimulator (if running) handle it.
        # For simple integration, we assume FillSimulator picks it up from queue if designed that way.
        # But here we are the handler.
        
        # NOTE: BacktestEngine usually handles fills via FillSimulator *after* order is placed.
        # This class might be redundant if BacktestEngine logic is hardcoded.
        # We'll leave it as a placeholder for the LiveEngine architecture.
        pass

try:
    import ccxt
    
    class CCXTExecutionHandler(ExecutionHandler):
        """
        Executes orders via CCXT (CryptoCom eXchange Trading Library).
        """
        def __init__(self, exchange_id: str, api_key: str, api_secret: str, sandbox: bool = True):
            self.exchange = getattr(ccxt, exchange_id)({
                'apiKey': api_key,
                'secret': api_secret,
                'enableRateLimit': True,
            })
            if sandbox:
                self.exchange.set_sandbox_mode(True)
                logger.info(f"Initialized {exchange_id} in Sandbox Mode")
            else:
                logger.warning(f"Initialized {exchange_id} in LIVE Mode")
                
        def execute_order(self, event: Event) -> None:
            if event.type != EventType.ORDER:
                return
                
            order: Order = event.data
            symbol = order.symbol.replace("BTCUSD", "BTC/USDT") # Map symbol
            side = order.side.lower()
            amount = float(order.quantity)
            price = float(order.price) if order.price else None
            
            try:
                if order.order_type == OrderType.MARKET:
                    logger.info(f"Sending MARKET {side} {amount} {symbol}")
                    # response = self.exchange.create_market_order(symbol, side, amount)
                    # For safety, we just log in this skeleton until tested
                    logger.info(f"CCXT: create_market_order({symbol}, {side}, {amount})")
                    
                elif order.order_type == OrderType.LIMIT:
                     logger.info(f"Sending LIMIT {side} {amount} {symbol} @ {price}")
                     # response = self.exchange.create_limit_order(symbol, side, amount, price)
                     logger.info(f"CCXT: create_limit_order({symbol}, {side}, {amount}, {price})")
                     
                else:
                    logger.error(f"Order Type {order.order_type} not supported in CCXT Handler yet.")

            except Exception as e:
                logger.error(f"CCXT Execution Failed: {e}")

except ImportError:
    logger.warning("CCXT not installed. Live Execution not available.")
    class CCXTExecutionHandler(ExecutionHandler):
        def execute_order(self, event: Event) -> None:
            logger.error("CCXT not installed.")

