package main

import (
	"encoding/binary"
	"encoding/json"
	"fmt"
	"log"
	"math"
	"time"
)

// DOCTRINE v2.0: The Fast Path
// This driver simulates the ingestion of Kingfisher Liquidation Alerts
// and their transcoding into GOLIATH's Internal SBE Format (Template ID 3).

// 1. External JSON Format (Kingfisher Mock)
type KingfisherAlert struct {
	Symbol    string  `json:"symbol"`
	Price     float64 `json:"price"`
	Volume    float64 `json:"volume"`
	Side      string  `json:"side"` // "long" or "short"
	Timestamp int64   `json:"timestamp"`
}

// 2. Internal SBE Format (Simplified Mock Structure)
// In production, this would be generated by sbe-tool from a .xml schema.
type MarketDataSBE struct {
	TemplateID uint16
	SchemaID   uint16
	Version    uint16
	SymbolID   uint32
	// Go doesn't have a direct binary Writer for int64, we often cast to uint64 for raw bytes
	Price     int64 // Fixed Point (e.g. 1.23456 -> 123456)
	Volume     uint64
	Flags      uint8 // Bitmask (e.g., 0x01 = Liquidation)
	Timestamp  uint64
}

// 3. The Transcoder (The Bridge)
func TranscodeAlert(alert KingfisherAlert) []byte {
	// A. Semantic Mapping
	var flags uint8 = 0
	flags |= 0x01 // Flag 0x01 = LIQUIDATION_EVENT
	if alert.Side == "short" {
		flags |= 0x02 // Flag 0x02 = SELL_SIDE
	}

	// B. Fixed Point Math (Price * 100,000)
	// NEVER use floats in the Engine!
	fixedPrice := int64(math.Round(alert.Price * 100000))

	// C. Hash Symbol to ID (Mock)
	// In a real system, we'd lookup "BTCUSD" -> 101 in a map
	symbolID := uint32(101) 

	// D. Build Struct (Conceptual)
	// We write directly to the buffer for speed, but here is the model:
	// sbe := MarketDataSBE{...}

	// E. Serialize to Binary (Little Endian)
	// In production, use the SBE library zero-copy buffer.
	// Total Size: 2+2+2+4+8+8+1+8 = 35 bytes + padding? Let's just say 36.
	buf := make([]byte, 36) 
	
	offset := 0
	binary.LittleEndian.PutUint16(buf[offset:], 3) // TemplateID
	offset += 2
	binary.LittleEndian.PutUint16(buf[offset:], 1) // SchemaID
	offset += 2
	binary.LittleEndian.PutUint16(buf[offset:], 1) // Version
	offset += 2
	binary.LittleEndian.PutUint32(buf[offset:], symbolID)
	offset += 4
	binary.LittleEndian.PutUint64(buf[offset:], uint64(fixedPrice)) 
	offset += 8
	binary.LittleEndian.PutUint64(buf[offset:], uint64(alert.Volume))
	offset += 8
	buf[offset] = flags
	offset += 1
	binary.LittleEndian.PutUint64(buf[offset:], uint64(alert.Timestamp))
	
	return buf
}

func main() {
	fmt.Println("GOLIATH :: Kingfisher Gateway Driver [Prototype]")
	fmt.Println("Status: LISTENING (Simulated WebSocket)")

	// Simulate incoming specific alert
	rawJSON := `{"symbol": "BTCUSD", "price": 45123.50, "volume": 1500000, "side": "long", "timestamp": 1700000000}`
	fmt.Printf("\n[Input] JSON Alert: %s\n", rawJSON)

	var alert KingfisherAlert
	if err := json.Unmarshal([]byte(rawJSON), &alert); err != nil {
		log.Fatal(err)
	}

	// Measure Latency
	start := time.Now()
	_ = TranscodeAlert(alert)
	duration := time.Since(start)
	
	// Create payload again for printing
	payload := TranscodeAlert(alert)

	fmt.Printf("[Core] SBE Transcoding Time: %v\n", duration)
	fmt.Printf("[Output] Binary Payload (Hex): %X\n", payload)
	fmt.Println("\n[Success] This payload is ready for the Rust Engine UDP Ring Buffer.")
}
